In [84]:
import pandas as pd
import pyxlsb

In [ ]:
def merge_csv_and_excel(csv_path, excel_path):
    csv = pd.read_csv(
        csv_path, 
        header=4,
        names=['date'] + [f"hour{i}" for i in range(1, 26)] # Rename column headers to: date, hour1,..., hour25
    )

    excel = pd.read_excel(
        excel_path,
        header=5,
        names=['date'] + [f"hour{i}" for i in range(1, 26)] # Rename column headers to: date, hour1,..., hour25
    )

    merged = pd.concat([csv, excel], ignore_index=True)
    merged['date'] = pd.to_datetime(merged['date'])

    return merged

CIEP = merge_csv_and_excel(
    csv_path='Data/Predict - y/JCPL/CIEP/Hist_JCP&L_CIEP-Eligible_Hourly_Load.csv', 
    excel_path='Data/Predict - y/JCPL/CIEP/JCP&L_CIEP-Eligible_Hourly_Load_August_2025_Update.xlsx'
)

RSCP = merge_csv_and_excel(
    csv_path='Data/Predict - y/JCPL/RSCP/Hist_JCP&L_RSCP-Eligible_Hourly_Load.csv',
    excel_path='Data/Predict - y/JCPL/RSCP/JCP&L_RSCP-Eligible_Hourly_Load_August_2025_Update.xlsx'
)

In [88]:
JCPL1 = pd.read_excel(
    'Data/Predict - y/JCPL/JCP&L_Historical_Hourly_Load_by_Class_Jun20-May23.xlsb',
    engine='pyxlsb',
    header=2,
)

# https://pypi.org/project/pyxlsb/
# dates will appear as floats in .xlsb files, convert_date(date) turns them into datetime instances.
JCPL1['Date'] = JCPL1['Date'].apply(pyxlsb.convert_date)
JCPL1

,Date,Hour,Res,GSTC,GSTI,GSC,GSI,GPC,GPI,GTC,GTI
0,2022-06-01,1,1758.083240,43.660331,11.139918,725.363908,47.005892,105.984666,59.448808,81.748799,91.241267
1,2022-06-01,2,1434.049390,41.963109,10.798187,680.209789,44.251682,102.524972,57.970587,80.401681,87.978270
2,2022-06-01,3,1391.249002,41.127830,10.640813,655.395751,42.595901,98.804259,58.502523,80.662481,85.580485
3,2022-06-01,4,1173.145301,42.852923,10.529662,619.497304,41.793511,99.692534,58.540017,80.586291,89.239141
4,2022-06-01,5,844.098606,46.584017,10.781928,577.885992,42.262087,104.073593,63.286557,82.054594,93.109678
...,...,...,...,...,...,...,...,...,...,...,...
8755,2023-05-31,20,1240.367291,49.780645,10.120440,779.055552,46.714467,101.156333,58.600216,87.566059,149.612309
8756,2023-05-31,21,1368.123527,46.069755,9.964598,785.199894,45.331185,96.405867,58.191321,85.054614,138.360570
8757,2023-05-31,22,1375.244616,41.300082,9.769970,737.307782,44.499599,91.401015,56.598500,81.071573,135.777801
8758,2023-05-31,23,1185.246402,39.273860,9.511936,669.754209,42.401514,87.011984,55.618926,79.657726,136.724256
8759,2023-05-31,24,1012.017802,6.469634,0.693984,456.207085,27.079711,4.578520,0.469451,3.154907,1.797884